"""
Database models for runs, plans, events, and artifacts.
"""

import uuid
from sqlalchemy import (
    Column,
    String,
    DateTime,
    JSON,
    Text,
    ForeignKey,
    Integer,
    Enum as SQLEnum,
    Boolean,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID
import enum

from app.core.database import Base


class RunStatus(str, enum.Enum):
    """Run status values."""
    PLANNING = "planning"  # Plan generation in progress
    AWAITING_APPROVAL = "awaiting_approval"
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    ABORTED = "aborted"


class Run(Base):
    """
    A run represents a single user query execution.
    Tracks the lifecycle from creation to completion.
    """

    __tablename__ = "runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    query = Column(Text, nullable=False)
    status = Column(
        SQLEnum(
            RunStatus,
            name="run_status",
            values_callable=lambda x: [e.value for e in x]
        ),
        nullable=False,
        default=RunStatus.AWAITING_APPROVAL
    )

    # Constraints provided by user
    constraints = Column(JSON, nullable=True)

    # Execution metadata
    selected_sources = Column(JSON, nullable=True)  # List of source names
    llm_provider_used = Column(String(50), nullable=True)
    error_summary = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=True)
    finished_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    plan = relationship("Plan", back_populates="run", uselist=False, cascade="all, delete-orphan")
    events = relationship("Event", back_populates="run", cascade="all, delete-orphan", order_by="Event.ts")
    artifacts = relationship("Artifact", back_populates="run", uselist=False, cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Run(id={self.id}, status='{self.status}')>"


class Plan(Base):
    """
    Execution plan generated by the coordinator agent.
    Requires user approval before execution.
    """

    __tablename__ = "plans"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, unique=True)
    version = Column(Integer, nullable=False, default=1)

    # Plan content
    steps = Column(JSON, nullable=False)  # List of step objects
    plan_json = Column(JSON, nullable=True)  # Full structured plan (schemas.plan.Plan)
    source_rationale = Column(JSON, nullable=True)  # List of source rationale objects

    # Approval
    approved = Column(String(10), nullable=True)  # 'true', 'false', or null
    approved_at = Column(DateTime(timezone=True), nullable=True)
    edits = Column(JSON, nullable=True)  # User edits to the plan

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationship
    run = relationship("Run", back_populates="plan")

    def __repr__(self):
        return f"<Plan(id={self.id}, run_id={self.run_id}, version={self.version})>"


class Event(Base):
    """
    Persisted event from agent execution.
    Follows the ReAct pattern: reason, action, observation, decision.
    """

    __tablename__ = "events"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True)

    # Event details
    agent = Column(String(50), nullable=False)  # coordinator, extraction, analytics, report
    phase = Column(String(50), nullable=False)  # reason, action, observation, decision
    message = Column(Text, nullable=False)
    payload = Column(JSON, nullable=False, default=dict)

    # Timestamp
    ts = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    # Relationship
    run = relationship("Run", back_populates="events")

    def __repr__(self):
        return f"<Event(id={self.id}, agent='{self.agent}', phase='{self.phase}')>"


class Artifact(Base):
    """
    Artifacts produced by a run: tables, charts, insights, and report markdown.
    """

    __tablename__ = "artifacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, unique=True)

    # Artifact content
    tables = Column(JSON, nullable=True)  # Dict of table name -> {columns, rows}
    charts = Column(JSON, nullable=True)  # Dict of chart name -> {plotly data}
    insights = Column(JSON, nullable=True)  # List of insight objects
    report_md = Column(Text, nullable=True)  # Markdown report

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationship
    run = relationship("Run", back_populates="artifacts")

    def __repr__(self):
        return f"<Artifact(id={self.id}, run_id={self.run_id})>"


class RunDatasetSnapshot(Base):
    """
    Run-scoped snapshot of the cleaned dataset used during execution.
    """

    __tablename__ = "run_dataset_snapshots"
    __table_args__ = (
        UniqueConstraint("run_id", "dataset_id", name="uq_run_dataset_snapshot"),
    )

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True)
    dataset_id = Column(Integer, ForeignKey("datasets.id", ondelete="CASCADE"), nullable=False, index=True)
    columns = Column(JSON, nullable=False)
    rows = Column(JSON, nullable=False)
    total_row_count = Column(Integer, nullable=False)
    is_truncated = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self):
        return f"<RunDatasetSnapshot(run_id={self.run_id}, dataset_id={self.dataset_id})>"
